### ISSUE TITLE
File doesn't exist during Logstash deploy

### ISSUE THREAD

**Issue by B3DTech** [3ilson/ansible-pfelk#10]
Ansible complains that it can't deploy 05-firewall.conf.  Looking at the source, it doesn't actually exist there, or in your repo.

It exists in the v6.1 tag, but not in master.

**Comment by a3ilson** [comment]
Thanks!  I just got done updating the main repo and will work on this one shortly.

**Comment by B3DTech** [comment]
Thanks.  Is Master branch recommended now, or should we stick to 6.1?  I see maxmind was removed from the master.

**Comment by a3ilson** [comment]
Give it another try (master branch).  I remove MaxMind and Java as both are bundled within Logstash.

**Comment by a3ilson** [comment]
Let me know if it works and I'll generate another release.

Thanks!

**Comment by B3DTech** [comment]
Installing on Ubuntu 20.04 fails.

TASK [logstash: Ensure Logstash is started and enabled on boot.]
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the request service Logstash: host"}

There is no systemd service file for Logstash.

**Comment by B3DTech** [comment]
Also looks like kibana binds to 127.0.0.1:5601 instead of 0.0.0.0

**Comment by a3ilson** [comment]
Thanks! I made the Kibana adjustment and corrected a syntax issue with the logstash/main.yml

I'm not that family with ansible so if your able to fix and/or provide a solution - we'd appreciated it.

**Comment by B3DTech** [comment]
OK - so I have the Logstash thing figured out I think.

When you create /etc/logstash/startup.options in the main.yaml, it ends up missing the actual required contents of startup.options required to create the service.  The JAVA_OPTS="@/etc/logstash/java_opts" needs to be in addition to the actual startup options.  You can find them here:  https://github.com/elastic/logstash/blob/master/config/startup.options

I copied this file over and appended the JAVA_OPTS to the end - worked fine.

Secondly, /etc/defaults/logstash is supposed to be file, not a directory, but it should be created by the installer.  I removed the file, and ran /usr/share/logstash/bin/system-install and it created it.

**Comment by a3ilson** [comment]
Updated and Travis-CI has validated.

Thanks!
