### ISSUE TITLE
Unable to install using Ansible

### ISSUE THREAD

**Issue by MySickSi** [3ilson/ansible-pfelk#12]
I followed the guide and attemtped to run the Ansible install but am presented with the below error.

```
TASK [elasticsearch : Debian - Add elasticsearch repository] ******************************************************************************************************************************************************************************************************************
failed: [localhost] (item={'repo': 'deb https://artifacts.elastic.co/packages/7.x/apt stable main', 'state': 'present'}) => {"ansible_loop_var": "item", "changed": false, "item": {"repo": "deb https://artifacts.elastic.co/packages/7.x/apt stable main", "state": "present"}, "msg": "apt cache update failed"}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by a3ilson** [comment]
@MySickSi - sorry for the delay...I am a bit busy for the next few months. 

Is the instance where you plan to install have internet accessibility? Doesn't appear to be an issue with the install but perhaps connectivity.

**Comment by fktkrt** [comment]
Hello, 
Unfortunately I cannot validate it at the moment, but yes, it looks like a connectivity/transient issue where you cannot update your apt packages.

Is the problem still persist?

You can find the actual variables used for the apt cache update under: https://github.com/pfelk/ansible/blob/main/group_vars/all.yml
One thing you could to is to try to execute these by hand on the target instance, and see whether that is working or not.

Please let us know how it works out!

**Comment by MySickSi** [comment]
Hi,

I was trying to run this on Ubuntu 20.04. I re-installed it on 18.04 and it's working now.
