### ISSUE TITLE
Testing the Ansible Galaxy Collection

### ISSUE THREAD

**Issue by fktkrt** [3ilson/ansible-pfelk#7]
I have just created an Ansible Galaxy Collection to package the playbook version of this solution.

You can find it here: https://galaxy.ansible.com/fktkrt/ansible_pfelk
Feel free to test it, and report back if you find any issues.

**Comment by fktkrt** [comment]
@revere521 can you run some tests maybe? You helped with testing the initial ansible-playbook as well.

**Comment by revere521** [comment]
Sure, I'll see if I can spin up a VM and try it out this evening

**Comment by revere521** [comment]
ok, playing the role of the end user here :) - assuming little or no knowledge of the ansible-galaxy command:"

i spun up an Ubuntu server VM in virtualbox, and run:

`ansible-galaxy collection install fktkrt.ansible_pfelk `

now what do I do?

Note, for the purposes of my test the management node and the ELK server are one in the same this time.

**Comment by fktkrt** [comment]
Yes, fair porint, I will complete the instructions.
If you did not specified any path, it should be in `~/.ansible/collections`
After that you can follow the installation steps described in README.

**Comment by revere521** [comment]
ok, skip the part when i clone the repository, but then do the rest. 

I don't think i see the hosts or deply-stack.yml files

**Comment by fktkrt** [comment]
Hm, looking at popular collections, it seems these are mostly included in the linked github repo, and/or the deploy method is usually done with the regular ansible-playbook way.

I'll look into it, if we can optimize this somehow.
In the meantime, can you finish the installation with the playbook and hosts included in this repo?

**Comment by revere521** [comment]
i appended the --connection=local to the command and it looks like it fails at the first task.  I'm not sure where to check where from the main.yml pulls the variable {java_archive}

![image](https://user-images.githubusercontent.com/23560313/79150915-91ed4080-7d97-11ea-8ca0-9f884fe5e347.png)

**Comment by fktkrt** [comment]
Variable locations should be fixed now, see release 1.0.5.
I am planning to setup a CI to test this automatically, currently I cannot access my setup. Until that, thank you for helping with the testing!

**Comment by revere521** [comment]
I left it to run overnight after your fix, and it ran fine - but failed because I hadn't setup the maxmind GeoIp.conf.   You may want to put in the instructions that step isn't optional; or find a way to have the ansible playbook not fail on that step. 

I set it up with my user and key, and I'm running it again - will confirm when it completes

**Comment by revere521** [comment]
it appears to run correctly and install the pfelk correctly now, looks good

**Comment by fktkrt** [comment]
Rewrote almost the whole geoipupdate role, introduced defaults variables, handlers, so now you can define your maxmind credentials at run-time in the playbook.

Rebuilt the Galaxy Collection with the latest changes and released the package in the repo as well and increased the quality score by eliminating some ansible-lint warnings.

Note: some refactor is still needed in the Java role, but that's unrelated to the Collection itself.

**Comment by AndreLFSMartins** [comment]
Hi, there is a apt cache update there is generating errors on ubuntu 20.04

**Comment by fktkrt** [comment]
Could you open a separate issue regarding this issue following the template provided in this repository?
